from tkinter import *
from tkinter import messagebox
a=Tk()
a.title("GUI Application")
a.geometry("500x500")
n=Label(a,text="Roll No : ")
n.grid(row=1,column=0)
e1=Entry(a)
e1.grid(row=1,column=1)
p=Label(a,text="Branch : ")
p.grid(row=2,column=0)
e2=Entry(a)
e2.grid(row=2,column=1)
b=Label(a,text="What courses are you learned")
b.grid(row=3,column=0)
cb1=Checkbutton(a,text="Python")
cb1.grid(row=4,column=0)
cb1=Checkbutton(a,text="C")
cb1.grid(row=5,column=0)
cb1=Checkbutton(a,text="C++")
cb1.grid(row=6,column=0)
cb1=Checkbutton(a,text="Java")
cb1.grid(row=7,column=0)
c=Label(a,text="Gender")
c.grid(row=8,column=0)
rb1=Radiobutton(a,text="Male",value=1)
rb1.grid(row=9,column=0)
rb2=Radiobutton(a,text="Female",value=2)
rb2.grid(row=9,column=1)
def fun():
    messagebox.showinfo("Hello","Successfully Submitted")
b1=Button(a,text="Submit",command=fun)
b1.grid(row=11,column=1)
a.mainloop()